services:
  app:
    build: .
    container_name: travelago
    restart: always
    env_file:
      '.env'
    environment:
      - DB_TYPE=mysql 
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=db_user
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8789
      - NODE_ENV=production
    ports:
      - '8789:8789'
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: 'db_user'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '${DB_ALLOW_EMPTY_PASSWORD}'
    ports:
      - '3333:3306'
    volumes:
      - mysql:/data/mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    container_name: redis
    restart: always

volumes:
  mysql:
    driver: local
